export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';
export const FETCH_QUIZ_BY_ID_SUCCESS = 'FETCH_QUIZ_BY_ID_SUCCESS';
export const FETCH_QUIZ_BY_ID_ERROR = 'FETCH_QUIZ_BY_ID_ERROR';

export const QUIZ_SET_ANSWER_STATE = 'QUIZ_SET_ANSWER_STATE';
export const QUIZ_FINISH = 'QUIZ_FINISH';
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION';
export const QUIZ_RETRY = 'QUIZ_RETRY';

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const QUIZ_POST_START = 'QUIZ_POST_START';
export const QUIZ_POST_SUCCESS = 'QUIZ_POST_SUCCESS';
export const QUIZ_POST_ERROR = 'QUIZ_POST_ERROR';
